-- ============================================================
--  AGROCESAR — Sistema de Monitoreo de Cultivos
--  Script DDL: 01_create_tables.sql
--  Motor: Oracle XE 18c / 21c
-- ============================================================
 
 
-- ============================================================
--  0. LIMPIEZA (ejecutar solo en entorno de desarrollo)
-- ============================================================
BEGIN
  FOR t IN (SELECT table_name FROM user_tables
            WHERE table_name IN (
              'ALERTAS','CULTIVOS_AGRICULTOR','CULTIVOS_CATALOGO',
              'MUNICIPIOS','USUARIOS'
            ))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/
 
BEGIN
  FOR s IN (SELECT sequence_name FROM user_sequences
            WHERE sequence_name IN (
              'SEQ_MUNICIPIOS','SEQ_USUARIOS',
              'SEQ_CULTIVOS_CATALOGO','SEQ_CULTIVOS_AGRICULTOR',
              'SEQ_ALERTAS'
            ))
  LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/
 

 
-- ============================================================
--  1. SECUENCIAS
-- ============================================================
CREATE SEQUENCE SEQ_MUNICIPIOS          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USUARIOS            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CULTIVOS_CATALOGO   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CULTIVOS_AGRICULTOR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALERTAS             START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
 
 
-- ============================================================
--  2. MUNICIPIOS
-- ============================================================
CREATE TABLE MUNICIPIOS (
  ID             NUMBER(10)    NOT NULL,
  NOMBRE         VARCHAR2(50) NOT NULL,
  DEPARTAMENTO   VARCHAR2(30)  DEFAULT 'Cesar' NOT NULL,
  LATITUD        NUMBER(8,6)   NOT NULL,
  LONGITUD       NUMBER(9,6)   NOT NULL,
  ACTIVO         NUMBER(1)     DEFAULT 1 NOT NULL,
  FECHA_CREACION DATE          DEFAULT SYSDATE NOT NULL,
 
  CONSTRAINT PK_MUNICIPIOS         PRIMARY KEY (ID),
  CONSTRAINT UQ_MUNICIPIOS_NOMBRE  UNIQUE (NOMBRE, DEPARTAMENTO),
  CONSTRAINT CK_MUNICIPIOS_ACTIVO  CHECK (ACTIVO IN (0, 1)),
  CONSTRAINT CK_MUNICIPIOS_LATITUD CHECK (LATITUD BETWEEN -90 AND 90),
  CONSTRAINT CK_MUNICIPIO_LONGITUD CHECK (LONGITUD BETWEEN -180 AND 180)
);
 
CREATE INDEX IDX_MUNICIPIOS_ACTIVO ON MUNICIPIOS(ACTIVO);
 
 
-- ============================================================
--  3. USUARIOS
-- ============================================================
CREATE TABLE USUARIOS (
  ID             NUMBER(10)    NOT NULL,
  NOMBRE         VARCHAR2(40)  NOT NULL,
  APELLIDO       VARCHAR2(40)  NOT NULL,
  EMAIL          VARCHAR2(120) NOT NULL,
  PASSWORD_HASH  VARCHAR2(255) NOT NULL,
  ROL            VARCHAR2(15)  NOT NULL,
  MUNICIPIO_ID   NUMBER(10),
  TELEFONO       VARCHAR2(13),
  ACTIVO         NUMBER(1)     DEFAULT 1 NOT NULL,
  FECHA_CREACION DATE          DEFAULT SYSDATE NOT NULL,
  ULTIMO_LOGIN   DATE,
 
  CONSTRAINT PK_USUARIOS           PRIMARY KEY (ID),
  CONSTRAINT UQ_USUARIOS_EMAIL     UNIQUE (EMAIL),
  CONSTRAINT CK_USUARIOS_EMAIL CHECK (
  REGEXP_LIKE(EMAIL, '^[a-zA-Z0-9_+&*-]+(\.[a-zA-Z0-9_+&*-]+)*@([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$')
  ),
  CONSTRAINT CK_USUARIOS_ROL       CHECK (ROL IN ('AGRICULTOR', 'ADMIN')),
  CONSTRAINT CK_USUARIOS_ACTIVO    CHECK (ACTIVO IN (0, 1)),
  CONSTRAINT CK_USUARIOS_TELEFONO  CHECK (TELEFONO IS NULL OR REGEXP_LIKE(TELEFONO, '^\+?(57)?[0-9]{10}$')),
  CONSTRAINT FK_USUARIOS_MUNICIPIO FOREIGN KEY (MUNICIPIO_ID) REFERENCES MUNICIPIOS(ID)
);
 
CREATE INDEX IDX_USUARIOS_ROL    ON USUARIOS(ROL);
CREATE INDEX IDX_USUARIOS_ACTIVO ON USUARIOS(ACTIVO);
 
 
-- ============================================================
--  4. CULTIVOS_CATALOGO
-- ============================================================
CREATE TABLE CULTIVOS_CATALOGO (
  ID                  NUMBER(10)    NOT NULL,
  NOMBRE              VARCHAR2(60) NOT NULL,
  DESCRIPCION         VARCHAR2(300),
  CATEGORIA           VARCHAR2(15)  DEFAULT 'TRANSITORIO' NOT NULL,
  TEMP_MIN            NUMBER(5,2)   NOT NULL,
  TEMP_MAX            NUMBER(5,2)   NOT NULL,
  LLUVIA_MIN          NUMBER(8,2)   NOT NULL,
  LLUVIA_MAX          NUMBER(8,2)   NOT NULL,
  HUMEDAD_MIN         NUMBER(5,2)   NOT NULL,
  HUMEDAD_MAX         NUMBER(5,2)   NOT NULL,
  TIPO_SUELO          VARCHAR2(20)  NOT NULL,
  DIAS_COSECHA_MIN    NUMBER(5)     NOT NULL,
  DIAS_COSECHA_MAX    NUMBER(5)     NOT NULL,
  FUENTE_DATOS        VARCHAR2(80),
  IMAGEN_URL          VARCHAR2(300),
  ACTIVO              NUMBER(1)     DEFAULT 1 NOT NULL,
  FECHA_CREACION      DATE          DEFAULT SYSDATE NOT NULL,
  FECHA_ACTUALIZACION DATE,
 
  CONSTRAINT PK_CULTIVOS_CATALOGO        PRIMARY KEY (ID),
  CONSTRAINT UQ_CULTIVOS_CATALOGO_NOMBRE UNIQUE (NOMBRE),
  CONSTRAINT CK_CATALOGO_CATEGORIA       CHECK (CATEGORIA IN ('TRANSITORIO', 'PERMANENTE')),
  CONSTRAINT CK_CATALOGO_ACTIVO          CHECK (ACTIVO IN (0, 1)),
  CONSTRAINT CK_CATALOGO_TEMP            CHECK (TEMP_MIN < TEMP_MAX),
  CONSTRAINT CK_CATALOGO_TEMP_RANGO      CHECK (TEMP_MIN >= -10 AND TEMP_MAX <= 50),
  CONSTRAINT CK_CATALOGO_TEMP_SPREAD     CHECK (TEMP_MAX - TEMP_MIN >= 2),
  CONSTRAINT CK_CATALOGO_LLUVIA_MIN      CHECK (LLUVIA_MIN >= 0),
  CONSTRAINT CK_CATALOGO_LLUVIA_RANGO    CHECK (LLUVIA_MIN < LLUVIA_MAX),
  CONSTRAINT CK_CATALOGO_LLUVIA_MAX      CHECK (LLUVIA_MAX > 0),
  CONSTRAINT CK_CATALOGO_LLUVIA_MAX_TOPE CHECK (LLUVIA_MAX <= 5000),
  CONSTRAINT CK_CATALOGO_HUMEDAD_MIN     CHECK (HUMEDAD_MIN BETWEEN 0 AND 100),
  CONSTRAINT CK_CATALOGO_HUMEDAD_RANGO   CHECK (HUMEDAD_MIN < HUMEDAD_MAX),
  CONSTRAINT CK_CATALOGO_HUMEDAD_MAX     CHECK (HUMEDAD_MAX BETWEEN 0 AND 100),
  CONSTRAINT CK_CATALOGO_DIAS            CHECK (DIAS_COSECHA_MIN > 0
                                             AND DIAS_COSECHA_MIN <= DIAS_COSECHA_MAX),
  CONSTRAINT CK_CATALOGO_TIPO_SUELO      CHECK (TIPO_SUELO IN (
    'Franco','Franco-arcilloso','Franco-arenoso',
    'Arcilloso','Arenoso','Limoso','Franco-limoso'
  ))
);
 
 
-- ============================================================
--  5. CULTIVOS_AGRICULTOR
-- ============================================================
CREATE TABLE CULTIVOS_AGRICULTOR (
  ID              NUMBER(10)    NOT NULL,
  USUARIO_ID      NUMBER(10)    NOT NULL,
  CATALOGO_ID     NUMBER(10)    NOT NULL,
  MUNICIPIO_ID    NUMBER(10)    NOT NULL,
  HECTAREAS       NUMBER(10,2)  NOT NULL,
  FECHA_SIEMBRA   DATE          NOT NULL,
 
  TEMP_MIN_OVERRIDE    NUMBER(5,2),
  TEMP_MAX_OVERRIDE    NUMBER(5,2),
  LLUVIA_MIN_OVERRIDE  NUMBER(8,2),
  LLUVIA_MAX_OVERRIDE  NUMBER(8,2),
  HUMEDAD_MIN_OVERRIDE NUMBER(5,2),
  HUMEDAD_MAX_OVERRIDE NUMBER(5,2),
 
  LATITUD_CULTIVO  NUMBER(8,6),
  LONGITUD_CULTIVO NUMBER(9,6),
 
  TIPO_SUELO      VARCHAR2(20),
 
  ACTIVO          NUMBER(1)     DEFAULT 1 NOT NULL,
  FECHA_CREACION  DATE          DEFAULT SYSDATE NOT NULL,
  FECHA_ACTUALIZACION DATE,
 
  CONSTRAINT PK_CULTIVOS_AGRICULTOR PRIMARY KEY (ID),
  CONSTRAINT FK_CULTAGR_USUARIO     FOREIGN KEY (USUARIO_ID)   REFERENCES USUARIOS(ID),
  CONSTRAINT FK_CULTAGR_CATALOGO    FOREIGN KEY (CATALOGO_ID)  REFERENCES CULTIVOS_CATALOGO(ID),
  CONSTRAINT FK_CULTAGR_MUNICIPIO   FOREIGN KEY (MUNICIPIO_ID) REFERENCES MUNICIPIOS(ID),
  CONSTRAINT CK_CULTAGR_ACTIVO      CHECK (ACTIVO IN (0, 1)),
  CONSTRAINT CK_CULTAGR_HECTAREAS   CHECK (HECTAREAS > 0 AND HECTAREAS <= 50000),
  CONSTRAINT CK_CULTAGR_TEMP_OVR    CHECK (
    TEMP_MIN_OVERRIDE IS NULL OR TEMP_MAX_OVERRIDE IS NULL
    OR TEMP_MIN_OVERRIDE < TEMP_MAX_OVERRIDE
  ),
  CONSTRAINT CK_CULTAGR_TEMP_MIN_OVR_RANGO  CHECK (
    TEMP_MIN_OVERRIDE IS NULL OR TEMP_MIN_OVERRIDE BETWEEN -10 AND 50
  ),
  CONSTRAINT CK_CULTAGR_TEMP_MAX_OVR_RANGO  CHECK (
    TEMP_MAX_OVERRIDE IS NULL OR TEMP_MAX_OVERRIDE BETWEEN -10 AND 50
  ),
  CONSTRAINT CK_CULTAGR_LLUVIA_OVR  CHECK (
    LLUVIA_MIN_OVERRIDE IS NULL OR LLUVIA_MAX_OVERRIDE IS NULL
    OR LLUVIA_MIN_OVERRIDE < LLUVIA_MAX_OVERRIDE
  ),
  CONSTRAINT CK_CULTAGR_LLUVIA_MIN_OVR_RANGO CHECK (
    LLUVIA_MIN_OVERRIDE IS NULL OR LLUVIA_MIN_OVERRIDE >= 0
  ),
  CONSTRAINT CK_CULTAGR_LLUVIA_MAX_OVR_RANGO CHECK (
    LLUVIA_MAX_OVERRIDE IS NULL OR LLUVIA_MAX_OVERRIDE <= 5000
  ),
  CONSTRAINT CK_CULTAGR_HUMEDAD_OVR CHECK (
    HUMEDAD_MIN_OVERRIDE IS NULL OR HUMEDAD_MAX_OVERRIDE IS NULL
    OR HUMEDAD_MIN_OVERRIDE < HUMEDAD_MAX_OVERRIDE
  ),
  CONSTRAINT CK_CULTAGR_HUMEDAD_MIN_OVR_RANGO CHECK (
    HUMEDAD_MIN_OVERRIDE IS NULL OR HUMEDAD_MIN_OVERRIDE BETWEEN 0 AND 100
  ),
  CONSTRAINT CK_CULTAGR_HUMEDAD_MAX_OVR_RANGO CHECK (
    HUMEDAD_MAX_OVERRIDE IS NULL OR HUMEDAD_MAX_OVERRIDE BETWEEN 0 AND 100
  ),
  CONSTRAINT CK_CULTAGR_TIPO_SUELO  CHECK (TIPO_SUELO IN (
    'Franco','Franco-arcilloso','Franco-arenoso',
    'Arcilloso','Arenoso','Limoso','Franco-limoso'
  ))
);
 
CREATE INDEX IDX_CULTAGR_USUARIO   ON CULTIVOS_AGRICULTOR(USUARIO_ID);
CREATE INDEX IDX_CULTAGR_MUNICIPIO ON CULTIVOS_AGRICULTOR(MUNICIPIO_ID);
CREATE INDEX IDX_CULTAGR_ACTIVO    ON CULTIVOS_AGRICULTOR(ACTIVO);
 
 
-- ============================================================
--  6. ALERTAS
-- ============================================================
CREATE TABLE ALERTAS (
  ID                    NUMBER(10)    NOT NULL,
  CULTIVO_AGRICULTOR_ID NUMBER(10)    NOT NULL,
  TIPO_ALERTA           VARCHAR2(25)  NOT NULL,
  SEVERIDAD             VARCHAR2(10)  NOT NULL,
  DESCRIPCION           VARCHAR2(300) NOT NULL,
  RECOMENDACION         VARCHAR2(500),
  FECHA_DIA_PRONOSTICO  DATE          NOT NULL,
  FECHA_GENERACION      DATE          DEFAULT SYSDATE NOT NULL,
  VALOR_DETECTADO       NUMBER(8,2)   NOT NULL,
  VALOR_UMBRAL          NUMBER(8,2)   NOT NULL,
  LEIDA                 NUMBER(1)     DEFAULT 0 NOT NULL,
  FECHA_LECTURA         DATE,
 
  CONSTRAINT PK_ALERTAS           PRIMARY KEY (ID),
  CONSTRAINT FK_ALERTAS_CULTIVO   FOREIGN KEY (CULTIVO_AGRICULTOR_ID)
    REFERENCES CULTIVOS_AGRICULTOR(ID),
  CONSTRAINT CK_ALERTAS_TIPO      CHECK (TIPO_ALERTA IN (
    'TEMPERATURA_ALTA',   'TEMPERATURA_BAJA',
    'LLUVIA_EXCESIVA',    'LLUVIA_INSUFICIENTE',
    'HUMEDAD_EXCESIVA',   'HUMEDAD_INSUFICIENTE'
  )),
  CONSTRAINT CK_ALERTAS_SEVERIDAD CHECK (SEVERIDAD IN ('ALTA','MEDIA','BAJA')),
  CONSTRAINT CK_ALERTAS_LEIDA     CHECK (LEIDA IN (0, 1)),
  CONSTRAINT UQ_ALERTAS_NODUP     UNIQUE (
    CULTIVO_AGRICULTOR_ID, TIPO_ALERTA, FECHA_DIA_PRONOSTICO
  )
);
 
CREATE INDEX IDX_ALERTAS_CULTIVO    ON ALERTAS(CULTIVO_AGRICULTOR_ID);
CREATE INDEX IDX_ALERTAS_TIPO       ON ALERTAS(TIPO_ALERTA);
CREATE INDEX IDX_ALERTAS_SEVERIDAD  ON ALERTAS(SEVERIDAD);
CREATE INDEX IDX_ALERTAS_FECHA_GEN  ON ALERTAS(FECHA_GENERACION);
CREATE INDEX IDX_ALERTAS_LEIDA      ON ALERTAS(LEIDA);
CREATE INDEX IDX_ALERTAS_FECHA_PRON ON ALERTAS(FECHA_DIA_PRONOSTICO);
 
 
-- ============================================================
--  7. VISTAS
-- ============================================================
CREATE OR REPLACE VIEW V_ALERTAS AS
SELECT
  a.ID                          AS ALERTA_ID,
  a.CULTIVO_AGRICULTOR_ID,
  u.NOMBRE || ' ' || u.APELLIDO AS AGRICULTOR,  
  ca.CATALOGO_ID,
  cc.NOMBRE                     AS CULTIVO,
  cc.CATEGORIA,
  ca.MUNICIPIO_ID,
  m.NOMBRE                      AS MUNICIPIO,
  a.TIPO_ALERTA,
  a.SEVERIDAD,
  a.DESCRIPCION,
  a.RECOMENDACION,
  a.VALOR_DETECTADO,
  a.VALOR_UMBRAL,
  a.FECHA_DIA_PRONOSTICO,
  a.FECHA_GENERACION,
  a.LEIDA,
  ca.USUARIO_ID,
  (TRUNC(ca.FECHA_SIEMBRA)
    + ROUND((cc.DIAS_COSECHA_MIN + cc.DIAS_COSECHA_MAX) / 2))
    - TRUNC(SYSDATE)       AS DIAS_RESTANTES_COSECHA
FROM ALERTAS a
JOIN CULTIVOS_AGRICULTOR ca ON a.CULTIVO_AGRICULTOR_ID = ca.ID
JOIN USUARIOS u             ON ca.USUARIO_ID  = u.ID
JOIN CULTIVOS_CATALOGO cc   ON ca.CATALOGO_ID = cc.ID
JOIN MUNICIPIOS m           ON ca.MUNICIPIO_ID = m.ID;
 
 
CREATE OR REPLACE VIEW V_CULTIVOS_CON_UMBRALES AS
SELECT
  ca.ID,
  ca.USUARIO_ID,
  u.NOMBRE || ' ' || u.APELLIDO                   AS AGRICULTOR,    
  u.TELEFONO,
  cc.NOMBRE                                       AS CULTIVO,
  cc.CATEGORIA,
  m.ID                                            AS MUNICIPIO_ID,
  m.NOMBRE                                        AS MUNICIPIO,
  NVL(ca.LATITUD_CULTIVO,  m.LATITUD)             AS LATITUD,
  NVL(ca.LONGITUD_CULTIVO, m.LONGITUD)            AS LONGITUD,
  ca.HECTAREAS,
  ca.FECHA_SIEMBRA,
  NVL(ca.TEMP_MIN_OVERRIDE,    cc.TEMP_MIN)       AS TEMP_MIN_EFECTIVA,
  NVL(ca.TEMP_MAX_OVERRIDE,    cc.TEMP_MAX)       AS TEMP_MAX_EFECTIVA,
  NVL(ca.LLUVIA_MIN_OVERRIDE,  cc.LLUVIA_MIN)     AS LLUVIA_MIN_EFECTIVA,
  NVL(ca.LLUVIA_MAX_OVERRIDE,  cc.LLUVIA_MAX)     AS LLUVIA_MAX_EFECTIVA,
  NVL(ca.HUMEDAD_MIN_OVERRIDE, cc.HUMEDAD_MIN)    AS HUMEDAD_MIN_EFECTIVA,
  NVL(ca.HUMEDAD_MAX_OVERRIDE, cc.HUMEDAD_MAX)    AS HUMEDAD_MAX_EFECTIVA,
  cc.DIAS_COSECHA_MIN,
  cc.DIAS_COSECHA_MAX,
  ROUND((cc.DIAS_COSECHA_MIN + cc.DIAS_COSECHA_MAX) / 2) AS DIAS_COSECHA_PROM,
  (TRUNC(ca.FECHA_SIEMBRA)
    + ROUND((cc.DIAS_COSECHA_MIN + cc.DIAS_COSECHA_MAX) / 2))
    - TRUNC(SYSDATE)                              AS DIAS_RESTANTES,
  ca.ACTIVO
FROM CULTIVOS_AGRICULTOR ca
JOIN USUARIOS u           ON ca.USUARIO_ID  = u.ID
JOIN CULTIVOS_CATALOGO cc ON ca.CATALOGO_ID = cc.ID
JOIN MUNICIPIOS m         ON ca.MUNICIPIO_ID = m.ID
WHERE u.ACTIVO  = 1
  AND ca.ACTIVO = 1
  AND cc.ACTIVO = 1;
 
 
-- ============================================================
--  FIN DEL SCRIPT
-- ============================================================