-- ============================================================
--  AGROCESAR — SISTEMA DE MONITOREO DE CULTIVOS
--  SCRIPT DDL: 04_TRIGGERS.SQL
--  MOTOR: ORACLE XE 18C / 21C
-- ============================================================

-- ============================================================
--  MUNICIPIOS
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_MUNICIPIOS_PK BEFORE
   INSERT ON MUNICIPIOS
   FOR EACH ROW
BEGIN
   :NEW.ID := SEQ_MUNICIPIOS.NEXTVAL;
END;
/

-- ============================================================
--  USUARIOS
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_USUARIOS_PK BEFORE
   INSERT ON USUARIOS
   FOR EACH ROW
BEGIN
   :NEW.ID := SEQ_USUARIOS.NEXTVAL;
END;
/

-- ============================================================
--  CULTIVOS_CATALOGO
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_CULTIVOS_CATALOGO_PK BEFORE
   INSERT ON CULTIVOS_CATALOGO
   FOR EACH ROW
BEGIN
   :NEW.ID := SEQ_CULTIVOS_CATALOGO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CATALOGO_FECHA_ACT BEFORE
   UPDATE ON CULTIVOS_CATALOGO
   FOR EACH ROW
BEGIN
   :NEW.FECHA_ACTUALIZACION := SYSDATE;
END;
/

-- ============================================================
--  CULTIVOS_AGRICULTOR
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_CULTIVOS_AGRICULTOR_PK BEFORE
   INSERT ON CULTIVOS_AGRICULTOR
   FOR EACH ROW
BEGIN
   :NEW.ID := SEQ_CULTIVOS_AGRICULTOR.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CULTAGR_FECHA_ACT BEFORE
   UPDATE ON CULTIVOS_AGRICULTOR
   FOR EACH ROW
BEGIN
   :NEW.FECHA_ACTUALIZACION := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDA_FECHA_SIEMBRA BEFORE
   INSERT OR UPDATE OF FECHA_SIEMBRA ON CULTIVOS_AGRICULTOR
   FOR EACH ROW
BEGIN
   IF :NEW.FECHA_SIEMBRA > TRUNC(SYSDATE) THEN
      RAISE_APPLICATION_ERROR(
         -20010,
         'LA FECHA DE SIEMBRA ('
         || TO_CHAR(
            :NEW.FECHA_SIEMBRA,
            'DD/MM/YYYY'
         )
         || ') NO PUEDE SER UNA FECHA FUTURA. FECHA MAXIMA PERMITIDA: '
         || TO_CHAR(
            TRUNC(SYSDATE),
            'DD/MM/YYYY'
         )
      );
   END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CATALOGO_DESACTIVAR_CASCADE AFTER
   UPDATE OF ACTIVO ON CULTIVOS_CATALOGO
   FOR EACH ROW
   WHEN ( NEW.ACTIVO = 0
      AND OLD.ACTIVO = 1 )
BEGIN
   UPDATE CULTIVOS_AGRICULTOR
      SET
      ACTIVO = 0
    WHERE CATALOGO_ID = :NEW.ID
      AND ACTIVO = 1;
END;
/

-- ============================================================
--  ALERTAS
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_ALERTAS_PK BEFORE
   INSERT ON ALERTAS
   FOR EACH ROW
BEGIN
   :NEW.ID := SEQ_ALERTAS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_ALERTAS_FECHA_LECTURA BEFORE
   UPDATE OF LEIDA ON ALERTAS
   FOR EACH ROW
   WHEN ( NEW.LEIDA = 1
      AND OLD.LEIDA = 0 )
BEGIN
   :NEW.FECHA_LECTURA := SYSDATE;
END;
/